### PR TITLE
Add forced libraries to the profile interface

### PR DESCRIPTION
**Pull request by LostDragonist**

### CODE REVIEW

**Comment by Holt59** [comment]
I'm not really fan of this because `IProfile` had not setters before this... Maybe this would be better in the game plugin? I guess you're already calling it there, no?

**Comment by LostDragonist** [comment]
No other plugin is calling these functions as they aren't accessible on any plugin interface. That's the entire point of this change.  

I don't really get the hesitance to add setters to the profile. They have to go somewhere. "We've never done this before" is some really weird logic. If anything, the fact that the setters aren't exposed on the plugin interface should be more of a red flag than anything.  Though if it's still a problem, sure, I can throw them on IOrganizer instead or something. /shrug.

**Comment by Holt59** [comment]
> No other plugin is calling these functions as they aren't accessible on any plugin interface. That's the entire point of this change.

My point was to add this to the game plugin rather than here, but not as "setXXX" but rather something that goes along "executables" or "executablesForcedLoad", or maybe in these classes?

> I don't really get the hesitance to add setters to the profile. They have to go somewhere. "We've never done this before" is some really weird logic. If anything, the fact that the setters aren't exposed on the plugin interface should be more of a red flag than anything.

That's only true if we actually want to expose way to modify the user profile. I'm not asking to move these to IOrganizer, which would be even worse. If we choose to allow plugins to modify a profile, then we should do it fully. What's weird is to have multiple getters but not setters except for one of the attributes.

**Comment by LostDragonist** [comment]
I'm not sure it belongs in the game plugin as I'd imagine there are other types of plugins that want to use it.  Regardless, this doesn't have an immediate use case so I'm just gonna scrap this.

**Pull request closed without merging**
