### PR TITLE
Moving things around

### PR DESCRIPTION
**Pull request by Qudix**

### CODE REVIEW

**Comment by Al12rs** [comment]
Can you change this one as well to use the new appconfig?

**Comment by Qudix** [comment]
This project doesn't have an AppConfig.

**Comment by Al12rs** [comment]
Sorry you are right, I thought you could access those with QCoreApplication

**Comment by isanae** [comment]
The `AppConfig` stuff is just a bunch of over engineered constant globals, it has nothing to do with Qt. This whole thing could be replaced with a couple of inlined functions in a header instead of having three stupid files with macros.

**Pull request merged**
