### PR TITLE
Add hasMasterExtension, hasLightExtension, isMasterFlagged, and isLightFlagged

### PR DESCRIPTION
**Pull request by Qudix**
Also deprecate isMaster, though I'm unsure if it's necessary to keep it here

### CODE REVIEW

**Comment by Al12rs** [comment]
Could you clarify in the comment what the differences in the functions are? I had to check the code to clear up whether isMasterFile only checked the extension or if it also included the flagged ones

**Comment by AnyOldName3** [comment]
I'm not sure the name `isMasterFile` is any better than `isMaster` was - it's still leaving the ambiguity about whether it's just checking the extension or the flag or some combination of the two. We've at least got the `isMasterFlagged` function now, which makes it clearer that it's probably not dealing with the flag, so the situation's somewhat improved whether or not the name changes. I'd suggest either coming up with a name that makes it clear it's only concerned about the filename, or leaving the name unchanged.

**Comment by Qudix** [comment]
Would the name `hasMasterExt` or `hasMasterExtension` be better?

**Comment by LostDragonist** [comment]
Those sound good to me (probably prefer the fully typed out one but eh)

**Review by LostDragonist — APPROVED** [review]

**Pull request merged**
